# Generated by Django 4.1.13 on 2023-12-23 12:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_data', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=100)),
            ],
        ),
    ]
