# Generated by Django 4.1.13 on 2023-12-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grid',
            old_name='grid_data',
            new_name='grid',
        ),
    ]
