# Generated by Django 4.1.13 on 2023-12-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0002_rename_grid_data_grid_grid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grid',
        ),
    ]
